# Generated by Django 5.0.6 on 2024-07-18 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_administrador_conf_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_cuenta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total_venta_iva',
        ),
        migrations.CreateModel(
            name='VentaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.PositiveIntegerField(verbose_name='Cantidad de productos')),
                ('subtotal_venta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de la venta')),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de la venta')),
                ('total_venta_iva', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de la venta con iva')),
                ('id_producto', models.ManyToManyField(to='app.producto', verbose_name='Producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'venta caja',
                'verbose_name_plural': 'ventas caja',
                'db_table': 'VentaCaja',
            },
        ),
    ]
