# Generated by Django 5.0.6 on 2024-07-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_venta_cantidad_producto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(choices=[('Caja', 'Caja'), ('Cuenta', 'Cuenta')], default='Caja', max_length=7, verbose_name='Tipo de Venta'),
        ),
    ]
