# Generated by Django 5.0.6 on 2024-07-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_venta_tipo_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='tipo_venta',
        ),
        migrations.AddField(
            model_name='ventacaja',
            name='metodo_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TF', 'Transferencia')], default='EF', max_length=3, verbose_name='Metodo de Pago'),
        ),
    ]
