# Generated by Django 5.0.6 on 2024-07-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_venta_metodo_pago_remove_venta_tipo_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventacaja',
            name='subtotal_venta',
        ),
    ]
