# Generated by Django 5.0.6 on 2024-06-14 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('RC', 'Registro Civil'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo_documento')),
                ('numero_documento', models.PositiveIntegerField(verbose_name='Numero_documento')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('RC', 'Registro Civil'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo_documento')),
                ('numero_documento', models.PositiveIntegerField(verbose_name='Numero_documento')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marcas',
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('RC', 'Registro Civil'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo_documento')),
                ('numero_documento', models.PositiveIntegerField(verbose_name='Numero_documento')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'mesero',
                'verbose_name_plural': 'meseros',
                'db_table': 'Mesero',
            },
        ),
        migrations.CreateModel(
            name='Metodo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('EF', 'Efectivo'), ('TF', 'Transferencia')], default='EF', max_length=2, verbose_name='Metodo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'metodo_pago',
                'verbose_name_plural': 'metodos_pago',
                'db_table': 'Metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('RC', 'Registro Civil'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo_documento')),
                ('numero_documento', models.PositiveIntegerField(verbose_name='Numero_documento')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('telefono', models.PositiveIntegerField(verbose_name='Telefono')),
                ('contraseña', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'operador',
                'verbose_name_plural': 'operadores',
                'db_table': 'Operador',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plato', models.CharField(max_length=50, verbose_name='Nombre_plato')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'plato',
                'verbose_name_plural': 'platos',
                'db_table': 'Plato',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(max_length=50, verbose_name='Presentacion')),
            ],
            options={
                'verbose_name': 'presentacion',
                'verbose_name_plural': 'presentaciones',
                'db_table': 'Presentacion',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Subtotal')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('id_mesero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mesero')),
                ('id_plato', models.ManyToManyField(to='app.plato')),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'db_table': 'Cuenta',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('id_marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
                ('id_presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.presentacion')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.PositiveIntegerField(verbose_name='Cantidad_producto')),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total_venta')),
                ('total_venta_iva', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total_venta_iva')),
                ('fecha_venta', models.DateTimeField(blank=True, verbose_name='Fecha_venta')),
                ('id_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.administrador')),
                ('id_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cuenta')),
                ('id_operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operador')),
                ('id_producto', models.ManyToManyField(to='app.producto')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'db_table': 'Venta',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision_factura', models.DateTimeField(blank=True, verbose_name='Fecha_emision_factura')),
                ('id_metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.metodo_pago')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venta')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'db_table': 'Factura',
            },
        ),
    ]
