# Generated by Django 5.1.1 on 2024-09-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision_factura',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la venta'),
        ),
    ]
