# Generated by Django 5.0.6 on 2024-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_categoria_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_producto',
            new_name='producto',
        ),
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(max_length=50, unique=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='presentacion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Presentacion'),
        ),
    ]
