# Generated by Django 5.1.1 on 2024-09-11 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_presentacion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presentacion',
            unique_together=set(),
        ),
    ]
