# Generated by Django 5.1.1 on 2024-09-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cliente_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cambio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='dinero_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dinero recibido'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total de la venta'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='venta',
            order_with_respect_to=None,
        ),
    ]
