# Generated by Django 5.1.1 on 2024-09-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_presentacion_presentacion'),
        ('app', '0003_alter_presentacion_unique_together'),
    ]

    operations = [
    ]
