# Generated by Django 5.1.1 on 2024-09-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_venta_cambio_venta_dinero_recibido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='subtotal_venta',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8, verbose_name='Subtotal'),
        ),
    ]
