# Generated by Django 5.0.6 on 2024-06-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_administrador_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='numero_documento',
            field=models.PositiveIntegerField(verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.PositiveIntegerField(verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('RC', 'Registro Civil'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='mesero',
            name='numero_documento',
            field=models.PositiveIntegerField(verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='mesero',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('RC', 'Registro Civil'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='numero_documento',
            field=models.PositiveIntegerField(verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de documento'),
        ),
    ]
