# Generated by Django 5.1.1 on 2024-09-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_merge_20240915_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presentacion',
            unique_together={('presentacion', 'unidad_medida')},
        ),
    ]
