# Generated by Django 5.0.6 on 2024-06-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_administrador_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='mesero',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, verbose_name='Numero de documento'),
        ),
    ]
