# Generated by Django 5.0.6 on 2024-06-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_administrador_numero_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plato',
            old_name='nombre_plato',
            new_name='plato',
        ),
    ]
