# Generated by Django 5.0.6 on 2024-06-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_nombre_plato_plato_plato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.PositiveIntegerField(max_length=11, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.presentacion'),
        ),
    ]
