# Generated by Django 5.0.6 on 2024-06-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cliente_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número de documento'),
        ),
    ]
