# Generated by Django 5.0.6 on 2024-06-24 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='id_metodo',
        ),
        migrations.AddField(
            model_name='venta',
            name='id_metodo',
            field=models.ForeignKey(default='EF', on_delete=django.db.models.deletion.CASCADE, to='app.metodo_pago'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.PositiveIntegerField(max_length=11, unique=True, verbose_name='Número de documento'),
        ),
    ]
