# Generated by Django 5.0.6 on 2024-06-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.IntegerField(max_length=11, unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='mesero',
            name='numero_documento',
            field=models.IntegerField(unique=True, verbose_name='Número de documento'),
        ),
    ]
