# Generated by Django 5.0.6 on 2024-06-24 14:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_cliente_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, validators=[app.models.Administrador.validar_numero_documento], verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, validators=[app.models.Cliente.validar_numero_documento], verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='mesero',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, validators=[app.models.Mesero.validar_numero_documento], verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, validators=[app.models.Operador.validar_numero_documento], verbose_name='Número de documento'),
        ),
    ]
