# Generated by Django 5.0.6 on 2024-06-24 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_mesero_pais_telefono_operador_pais_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
