# Generated by Django 5.0.6 on 2024-06-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_administrador_email_alter_mesero_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='id_metodo',
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.presentacion', verbose_name='Presentación'),
        ),
        migrations.DeleteModel(
            name='Metodo_pago',
        ),
    ]
