# Generated by Django 5.0.6 on 2024-06-25 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_factura_id_metodo_alter_producto_id_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TF', 'Transferencia')], default='EF', max_length=3, verbose_name='Metodo de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.administrador', verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cuenta', verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.operador', verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_producto',
            field=models.ManyToManyField(to='app.producto', verbose_name='Producto'),
        ),
    ]
