# Generated by Django 5.0.6 on 2024-06-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_administrador_conf_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='conf_contraseña',
            field=models.CharField(default='', max_length=50, verbose_name='Confirmación de contraseña'),
        ),
    ]
