# Generated by Django 5.0.7 on 2024-07-25 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_administrador_email_administrador_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterField(
            model_name='administrador',
            name='conf_contraseña',
            field=models.CharField(default='', max_length=128, verbose_name='Confirmación de contraseña'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='contraseña',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Contraseña'),
        ),
    ]
