# Generated by Django 5.0.7 on 2024-07-25 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_administrador_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='conf_contraseña',
            new_name='conf_contrasena',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='contraseña',
            new_name='contrasena',
        ),
    ]
