# Generated by Django 5.0.7 on 2024-07-25 19:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_conf_contraseña_administrador_conf_contrasena_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operador',
            options={'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.RemoveField(
            model_name='operador',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='pais_telefono',
        ),
        migrations.AddField(
            model_name='operador',
            name='conf_contrasena',
            field=models.CharField(default='', max_length=128, verbose_name='Confirmación de contraseña'),
        ),
        migrations.AddField(
            model_name='operador',
            name='contrasena',
            field=models.CharField(default=1, max_length=128, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operador',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
