# Generated by Django 5.0.7 on 2024-08-02 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_operador_options_remove_operador_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='venta',
            order_with_respect_to='fecha_venta',
        ),
        migrations.CreateModel(
            name='Detalle_venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.PositiveIntegerField(verbose_name='Cantidad de productos')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de la venta')),
                ('total_venta_iva', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de la venta con iva')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ManyToManyField(to='app.producto', verbose_name='Producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.venta')),
            ],
            options={
                'verbose_name': 'detalle_de_venta',
                'verbose_name_plural': 'detalles_de_ventas',
                'db_table': 'Detalle_venta',
                'order_with_respect_to': 'creacion',
            },
        ),
        migrations.CreateModel(
            name='Detalle_venta_cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.PositiveIntegerField(verbose_name='Cantidad de productos')),
                ('cantidad_plato', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de la venta')),
                ('total_venta_iva', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Total de la venta con iva')),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cliente')),
                ('id_mesero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.mesero')),
                ('id_plato', models.ManyToManyField(to='app.plato')),
                ('id_producto', models.ManyToManyField(to='app.producto', verbose_name='Producto')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.venta')),
            ],
            options={
                'verbose_name': 'detalle_venta_cuenta',
                'verbose_name_plural': 'detalles_venta_cuentas',
                'db_table': 'Detalle_venta_cuenta',
                'order_with_respect_to': 'creacion',
            },
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_admin',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_cuenta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_operador',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_producto',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
