# Generated by Django 5.0.7 on 2024-07-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_operador_options_remove_operador_contraseña_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'permissions': [], 'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EF', 'Efectivo'), ('TF', 'Transferencia')], default='EF', max_length=3, verbose_name='Método de Pago'),
        ),
    ]
