# Generated by Django 5.0.7 on 2024-08-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_venta_order_with_respect_to_detalle_venta_and_more'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='detalle_venta',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='detalle_venta_cuenta',
            order_with_respect_to=None,
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='creacion',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='total_venta',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='total_venta_iva',
        ),
        migrations.RemoveField(
            model_name='detalle_venta_cuenta',
            name='creacion',
        ),
        migrations.RemoveField(
            model_name='detalle_venta_cuenta',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='detalle_venta_cuenta',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='detalle_venta_cuenta',
            name='total_venta',
        ),
        migrations.RemoveField(
            model_name='detalle_venta_cuenta',
            name='total_venta_iva',
        ),
    ]
