# Generated by Django 5.0.7 on 2024-08-08 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_venta_total_venta_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='detalle_venta_cuenta',
            name='id_plato',
        ),
        migrations.RemoveField(
            model_name='detalle_venta_cuenta',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='id_producto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='app.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_venta_cuenta',
            name='id_plato',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='app.plato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_venta_cuenta',
            name='id_producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.producto'),
            preserve_default=False,
        ),
    ]
