# Generated by Django 5.0.7 on 2024-08-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_detalle_venta_id_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de venta'),
        ),
    ]
