# Generated by Django 5.1 on 2024-08-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_venta_order_with_respect_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='unidad_medida',
            field=models.CharField(choices=[('l', 'litros'), ('ml', 'mililitros'), ('g', 'gramos')], default='', max_length=3, verbose_name='Tipo de documento'),
        ),
    ]
