# Generated by Django 5.1 on 2024-08-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_venta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'enta', 'verbose_name_plural': 'ventas'},
        ),
    ]
