# Generated by Django 5.1 on 2024-08-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_venta_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha_venta',
        ),
    ]
