# Generated by Django 5.1 on 2024-08-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_venta_fecha_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(auto_now=True, verbose_name='Fecha de la venta'),
        ),
    ]
