# Generated by Django 5.1 on 2024-08-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_venta_fecha_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha_venta',
        ),
    ]
