# Generated by Django 5.1.1 on 2024-09-04 21:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_presentacion_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número de documento'),
        ),
    ]
