# Generated by Django 5.1 on 2024-08-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_detalle_venta_subtotal_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=' ', max_digits=8, verbose_name='Total de la venta'),
        ),
    ]
