# Generated by Django 5.1.1 on 2024-09-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_presentacion_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentacion',
            name='presentacion',
            field=models.CharField(max_length=50, unique=True, verbose_name='Presentación'),
        ),
    ]
