# Generated by Django 5.1 on 2024-08-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'verbose_name': 'venta', 'verbose_name_plural': 'ventas'},
        ),
    ]
