# Generated by Django 5.1.1 on 2024-09-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_presentacion_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='numero_documento',
            field=models.PositiveIntegerField(verbose_name='Número de documento'),
        ),
    ]
