# Generated by Django 5.1 on 2024-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_venta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cambio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='dinero_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Dinero recibido'),
        ),
    ]
