# Generated by Django 5.1 on 2024-09-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_venta_cambio_venta_dinero_recibido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_venta',
            old_name='subtotal_venta',
            new_name='subtotal',
        ),
        migrations.AddField(
            model_name='detalle_venta_cuenta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='detalle_venta_cuenta',
            name='subtotal_plato',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8, verbose_name='Subtotal'),
        ),
    ]
