# Generated by Django 5.1 on 2024-09-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_rename_subtotal_venta_detalle_venta_subtotal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_venta',
            old_name='subtotal',
            new_name='subtotal_venta',
        ),
        migrations.RenameField(
            model_name='detalle_venta_cuenta',
            old_name='subtotal',
            new_name='subtotal_producto',
        ),
    ]
