# Generated by Django 5.1 on 2024-09-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_rename_subtotal_detalle_venta_subtotal_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta_cuenta',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='detalle_venta_cuenta',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='detalle_venta_cuenta',
            name='subtotal_producto',
        ),
    ]
