# Generated by Django 5.1 on 2024-09-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_detalle_venta_cuenta_cantidad_producto_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle_venta_cuenta',
            new_name='Cuenta',
        ),
    ]
